package genrules

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// repoRoot はテストから見たリポジトリの根 (go/internal/genrules の 3 つ上)。
func repoRoot() string { return filepath.Join("..", "..", "..") }

// fixture はリポの規約データを写した使い捨ての根を作り、docs を置いて返す。
func fixture(t *testing.T, docs map[string]string) string {
	t.Helper()
	root := t.TempDir()
	rules, err := os.ReadFile(filepath.Join(repoRoot(), RulesPath))
	if err != nil {
		t.Fatal(err)
	}
	docs[RulesPath] = string(rules)
	for rel, body := range docs {
		path := filepath.Join(root, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return root
}

// allDocs はリポのルールが要る doc をぜんぶ小さな中身で置く。
func allDocs(t *testing.T) map[string]string {
	t.Helper()
	rules, err := LoadRules(repoRoot())
	if err != nil {
		t.Fatal(err)
	}
	docs := map[string]string{}
	for _, spec := range rules.Rules {
		docs[spec.Src] = "# " + spec.Out + " の本文\n"
	}
	return docs
}

func run(t *testing.T, root string, args []string, opts Options) (string, string, int) {
	t.Helper()
	var out, errOut strings.Builder
	code, err := Run(&out, &errOut, root, args, opts)
	if err != nil {
		t.Fatalf("Run が失敗した: %v", err)
	}
	return out.String(), errOut.String(), code
}

func read(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(data)
}

func TestGeneratesHeaderAndBody(t *testing.T) {
	root := fixture(t, allDocs(t))
	out, errOut, code := run(t, root, nil, Options{})
	if code != 0 {
		t.Fatalf("終了コードが %d (期待 0)\n%s%s", code, out, errOut)
	}
	if !strings.HasPrefix(out, "wrote .claude/rules/drawing.md <- docs/drawing-floor.md\n") {
		t.Errorf("書き出しの報告が違う:\n%s", out)
	}
	got := read(t, filepath.Join(root, ".claude", "rules", "flix.md"))
	want := "---\npaths:\n  - \"**/*.flix\"\n---\n\n" +
		"<!-- generated by bin/gen-rules.py from docs/flix-conventions.md — " +
		"編集しないで。本文は docs/flix-conventions.md を直して make rules -->\n" +
		"# flix.md の本文\n"
	if got != want {
		t.Errorf("生成した .md が違う:\n%q\n期待:\n%q", got, want)
	}
}

func TestSecondRunWritesNothing(t *testing.T) {
	root := fixture(t, allDocs(t))
	run(t, root, nil, Options{})
	out, errOut, code := run(t, root, nil, Options{})
	if code != 0 || out != "" || errOut != "" {
		t.Errorf("2 回目に何か出た: %d %q %q", code, out, errOut)
	}
}

func TestCheckIsGreenAfterGenerate(t *testing.T) {
	root := fixture(t, allDocs(t))
	run(t, root, nil, Options{})
	out, _, code := run(t, root, []string{"--check"}, Options{})
	if code != 0 {
		t.Fatalf("生成直後の --check が %d", code)
	}
	if out != "[gen-rules] OK: .claude/rules と agents-pack/rules は docs/ と一致しています\n" {
		t.Errorf("--check の OK が違う: %q", out)
	}
}

func TestCheckWritesNothing(t *testing.T) {
	root := fixture(t, allDocs(t))
	out, errOut, code := run(t, root, []string{"--check"}, Options{})
	if code != 1 {
		t.Fatalf("何も生成していないのに --check が %d", code)
	}
	if out != "" {
		t.Errorf("--check が stdout に出した: %q", out)
	}
	if !strings.HasSuffix(errOut, "`make rules` で作り直してください。\n") {
		t.Errorf("--check の締めが違う:\n%s", errOut)
	}
	if _, err := os.Stat(filepath.Join(root, ".claude")); err == nil {
		t.Error("--check なのに書き出し先を作った")
	}
}

func TestStaleLineNamesBothSides(t *testing.T) {
	root := fixture(t, allDocs(t))
	_, errOut, _ := run(t, root, []string{"--check"}, Options{})
	want := "agents-pack/rules/flix.md が docs/flix-conventions.md とずれています\n"
	if !strings.Contains(errOut, want) {
		t.Errorf("ずれの行が違う:\n%s", errOut)
	}
}

func TestMissingSourceDocStopsAtOne(t *testing.T) {
	docs := allDocs(t)
	delete(docs, "docs/flix-conventions.md")
	root := fixture(t, docs)
	out, errOut, code := run(t, root, nil, Options{})
	if code != 1 {
		t.Fatalf("元の doc が無いのに終了コードが %d", code)
	}
	if errOut != "元の doc がありません: docs/flix-conventions.md\n" {
		t.Errorf("断り方が違う: %q", errOut)
	}
	// 手前の 1 本は書けている（Python も止まる前に書く）。
	if !strings.Contains(out, "wrote .claude/rules/drawing.md") {
		t.Errorf("手前の 1 本を書いていない: %q", out)
	}
}

func TestOutDirRedirectsWrites(t *testing.T) {
	root := fixture(t, allDocs(t))
	outBase := t.TempDir()
	out, _, code := run(t, root, nil, Options{OutBase: outBase})
	if code != 0 {
		t.Fatalf("--out で %d", code)
	}
	if !strings.Contains(out, "wrote .claude/rules/drawing.md <- docs/drawing-floor.md") {
		t.Errorf("報告の字面が --out で変わった:\n%s", out)
	}
	if _, err := os.Stat(filepath.Join(outBase, ".claude", "rules", "drawing.md")); err != nil {
		t.Errorf("--out の先に書いていない: %v", err)
	}
	if _, err := os.Stat(filepath.Join(root, ".claude")); err == nil {
		t.Error("--out を渡したのに元の根へ書いた")
	}
}

func TestCRLFOnDiskIsNotRewritten(t *testing.T) {
	root := fixture(t, allDocs(t))
	run(t, root, nil, Options{})
	path := filepath.Join(root, ".claude", "rules", "flix.md")
	body := read(t, path)
	if err := os.WriteFile(path, []byte(strings.ReplaceAll(body, "\n", "\r\n")), 0o644); err != nil {
		t.Fatal(err)
	}
	out, _, _ := run(t, root, nil, Options{})
	if strings.Contains(out, ".claude/rules/flix.md") {
		t.Errorf("行末だけ違う物を書き直した:\n%s", out)
	}
}

func TestBothOutDirsGetTheSameBytes(t *testing.T) {
	root := fixture(t, allDocs(t))
	run(t, root, nil, Options{})
	a := read(t, filepath.Join(root, ".claude", "rules", "drawing.md"))
	b := read(t, filepath.Join(root, "agents-pack", "rules", "drawing.md"))
	if a != b {
		t.Error(".claude/rules と agents-pack/rules の中身が違う")
	}
}

func TestMissingRulesDataAborts(t *testing.T) {
	var out, errOut strings.Builder
	code, err := Run(&out, &errOut, t.TempDir(), nil, Options{})
	if err == nil {
		t.Fatal("規約データが無いのにエラーを返さなかった")
	}
	if code == 0 {
		t.Errorf("規約データが無いのに終了コード 0")
	}
	if out.String() != "" {
		t.Errorf("規約が読めないのに何か出力した: %q", out.String())
	}
}
