[package]
name        = "javafx_hello"
description = "Flix + JavaFX hello world spike"
version     = "0.1.0"
flix        = "0.73.0"
authors     = ["ababup1192 <ababup1192@gmail.com>"]

[mvn-dependencies]
"org.openjfx:javafx-base"     = "21.0.5"
"org.openjfx:javafx-graphics" = "21.0.5"
"org.openjfx:javafx-controls" = "21.0.5"
"org.openjfx:javafx-fxml"     = "21.0.5"
"org.openjfx:javafx-swing"    = "21.0.5"
"org.lwjgl:lwjgl"             = "3.4.1"
"org.lwjgl:lwjgl-opengl"      = "3.4.1"
"org.lwjglx:lwjgl3-awt"       = "0.2.4"
"org.lwjgl:lwjgl-jawt"        = "3.4.1"

[jar-dependencies]
"javafx-base-21.0.5-mac-aarch64.jar"         = "url:https://repo1.maven.org/maven2/org/openjfx/javafx-base/21.0.5/javafx-base-21.0.5-mac-aarch64.jar"
"javafx-graphics-21.0.5-mac-aarch64.jar"     = "url:https://repo1.maven.org/maven2/org/openjfx/javafx-graphics/21.0.5/javafx-graphics-21.0.5-mac-aarch64.jar"
"javafx-controls-21.0.5-mac-aarch64.jar"     = "url:https://repo1.maven.org/maven2/org/openjfx/javafx-controls/21.0.5/javafx-controls-21.0.5-mac-aarch64.jar"
"javafx-fxml-21.0.5-mac-aarch64.jar"         = "url:https://repo1.maven.org/maven2/org/openjfx/javafx-fxml/21.0.5/javafx-fxml-21.0.5-mac-aarch64.jar"
"javafx-swing-21.0.5-mac-aarch64.jar"        = "url:https://repo1.maven.org/maven2/org/openjfx/javafx-swing/21.0.5/javafx-swing-21.0.5-mac-aarch64.jar"
"lwjgl-3.4.1-natives-macos-arm64.jar"        = "url:https://repo1.maven.org/maven2/org/lwjgl/lwjgl/3.4.1/lwjgl-3.4.1-natives-macos-arm64.jar"
"lwjgl-opengl-3.4.1-natives-macos-arm64.jar" = "url:https://repo1.maven.org/maven2/org/lwjgl/lwjgl-opengl/3.4.1/lwjgl-opengl-3.4.1-natives-macos-arm64.jar"
