[package]
name        = "flix_engine_editor"
description = "Built-in editor (Godot-inspired) for flix_game_engine"
version     = "0.1.0"
flix        = "0.72.0"
authors     = ["ababup1192 <ababup1192@gmail.com>"]
repository  = "github:ababup1192/flix_engine_editor"

[dependencies]
"github:mlutze/flix-json" = "0.13.2"
"github:ababup1192/flix_game_engine" = { version = "0.1.0", security = "unrestricted" }
