[package]
name        = "flix_engine_editor"
description = "Built-in editor (Godot-inspired) for flix_game_engine"
version     = "0.1.0"
flix        = "0.72.0"
authors     = ["ababup1192 <ababup1192@gmail.com>"]
repository  = "github:ababup1192/flix_engine_editor"

[dependencies]
"github:mlutze/flix-json" = "0.13.2"
"github:ababup1192/flix_game_engine" = { version = "0.1.0", security = "unrestricted" }

[mvn-dependencies]
"com.formdev:flatlaf" = "3.7.1"
"org.lwjgl:lwjgl" = "3.3.5"
"org.lwjgl:lwjgl-glfw" = "3.3.5"
"org.lwjgl:lwjgl-jawt" = "3.3.5"
"org.lwjgl:lwjgl-opengl" = "3.3.5"
"org.lwjgl:lwjgl-stb" = "3.3.5"
"org.lwjgl:lwjgl-openal" = "3.3.5"
"org.lwjglx:lwjgl3-awt" = "0.2.4"

[jar-dependencies]
"lwjgl-3.3.5-natives-macos-arm64.jar" = "url:https://repo1.maven.org/maven2/org/lwjgl/lwjgl/3.3.5/lwjgl-3.3.5-natives-macos-arm64.jar"
"lwjgl-glfw-3.3.5-natives-macos-arm64.jar" = "url:https://repo1.maven.org/maven2/org/lwjgl/lwjgl-glfw/3.3.5/lwjgl-glfw-3.3.5-natives-macos-arm64.jar"
"lwjgl-opengl-3.3.5-natives-macos-arm64.jar" = "url:https://repo1.maven.org/maven2/org/lwjgl/lwjgl-opengl/3.3.5/lwjgl-opengl-3.3.5-natives-macos-arm64.jar"
"lwjgl-stb-3.3.5-natives-macos-arm64.jar" = "url:https://repo1.maven.org/maven2/org/lwjgl/lwjgl-stb/3.3.5/lwjgl-stb-3.3.5-natives-macos-arm64.jar"
"lwjgl-openal-3.3.5-natives-macos-arm64.jar" = "url:https://repo1.maven.org/maven2/org/lwjgl/lwjgl-openal/3.3.5/lwjgl-openal-3.3.5-natives-macos-arm64.jar"
