package syncagents

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// fixture は使い捨ての配り元を作る。規約データだけはリポの物を写す。
func fixture(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	rules, err := os.ReadFile(filepath.Join(repoRoot(), RulesPath))
	if err != nil {
		t.Fatal(err)
	}
	write(t, root, RulesPath, string(rules), 0o644)
	write(t, root, "agents-pack/AGENTS.core.md", "# core\n\n本文\n\n\n", 0o644)
	write(t, root, "agents-pack/skills/alpha/SKILL.md",
		"---\nname: alpha\ndescription: \"能書き。〜のときに使う。補足。\"\n---\n", 0o644)
	write(t, root, "agents-pack/skills/beta/SKILL.md",
		"---\ndescription: 引き金の無い説明。おまけ。\n---\n", 0o644)
	if err := os.MkdirAll(filepath.Join(root, "agents-pack", "skills", "gamma"), 0o755); err != nil {
		t.Fatal(err)
	}
	write(t, root, "agents-pack/rules/b.md", ".claude/skills/alpha/SKILL.md\n", 0o644)
	write(t, root, "agents-pack/rules/a.md", "x\n", 0o644)
	write(t, root, "docs/link.md", ".claude/skills/nope/SKILL.md\n", 0o644)
	write(t, root, "bin/lint-fake.py", "#!/usr/bin/env python3\n", 0o755)
	write(t, root, "bin/plain.txt", "y\n", 0o644)
	write(t, root, "agents-pack/manifest.json", `{
	  "copy": [{"src": "bin/lint-fake.py", "dst": "bin/lint-fake.py"},
	           {"src": "bin/plain.txt", "dst": "bin/plain.txt"}],
	  "copyIfAbsent": [{"src": "bin/plain.txt", "dst": ".claude/settings.json"}],
	  "copyDirs": [{"src": "agents-pack/skills", "dst": ".claude/skills"}]
	}`, 0o644)
	return root
}

func write(t *testing.T, root, rel, body string, mode os.FileMode) {
	t.Helper()
	path := filepath.Join(root, filepath.FromSlash(rel))
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(body), mode); err != nil {
		t.Fatal(err)
	}
	if err := os.Chmod(path, mode); err != nil {
		t.Fatal(err)
	}
}

func run(t *testing.T, root string, args ...string) (string, string, int) {
	t.Helper()
	var out, errOut strings.Builder
	code, err := Run(&out, &errOut, root, args)
	if err != nil {
		t.Fatalf("止まってしまった: %v", err)
	}
	return out.String(), errOut.String(), code
}

func TestSyncWritesAgentsMd(t *testing.T) {
	root := fixture(t)
	game := t.TempDir()
	out, errOut, code := run(t, root, "--game", game, "--version", "1.2.3")
	if code != 0 || errOut != "" {
		t.Fatalf("code=%d err=%q", code, errOut)
	}
	if !strings.Contains(out, "[sync-agents] skill: alpha\n") {
		t.Errorf("skill の一覧が出ていない: %q", out)
	}
	body, err := os.ReadFile(filepath.Join(game, "AGENTS.md"))
	if err != nil {
		t.Fatal(err)
	}
	want := "<!-- generated by flix_game_engine agents-pack (engine v1.2.3)." +
		" 編集しないで。共通部は engine の agents-pack/AGENTS.core.md、" +
		"ゲーム固有部は AGENTS.local.md を編集して再 sync -->\n\n" +
		"# core\n\n本文\n\n" +
		"## 配られているスキル一覧（sync-agents が自動生成。手で編集しない）\n\n" +
		"- `.claude/skills/alpha/SKILL.md` — 〜のときに使う。\n" +
		"- `.claude/skills/beta/SKILL.md` — 引き金の無い説明。\n" +
		"- `.claude/skills/gamma/SKILL.md` — \n"
	if string(body) != want {
		t.Errorf("AGENTS.md が\n%q\n期待\n%q", string(body), want)
	}
}

func TestSyncWritesClaudeMd(t *testing.T) {
	root := fixture(t)
	game := t.TempDir()
	run(t, root, "--game", game)
	body, err := os.ReadFile(filepath.Join(game, "CLAUDE.md"))
	if err != nil {
		t.Fatal(err)
	}
	if string(body) != "@AGENTS.md\n" {
		t.Errorf("CLAUDE.md が %q", string(body))
	}
}

func TestSyncAppendsLocalDoc(t *testing.T) {
	root := fixture(t)
	game := t.TempDir()
	write(t, game, "AGENTS.local.md", "ゲーム固有\n\n\n", 0o644)
	run(t, root, "--game", game)
	body, err := os.ReadFile(filepath.Join(game, "AGENTS.md"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasSuffix(string(body), "gamma/SKILL.md` — \n\nゲーム固有\n") {
		t.Errorf("AGENTS.local.md の付き方が違う: %q", string(body))
	}
}

func TestSyncKeepsExecutableBit(t *testing.T) {
	root := fixture(t)
	game := t.TempDir()
	run(t, root, "--game", game)
	info, err := os.Stat(filepath.Join(game, "bin", "lint-fake.py"))
	if err != nil {
		t.Fatal(err)
	}
	if info.Mode().Perm()&0o111 == 0 {
		t.Errorf("実行ビットが落ちている: %v", info.Mode())
	}
	plain, err := os.Stat(filepath.Join(game, "bin", "plain.txt"))
	if err != nil {
		t.Fatal(err)
	}
	if plain.Mode().Perm()&0o111 != 0 {
		t.Errorf("実行ビットが勝手に付いている: %v", plain.Mode())
	}
}

func TestSyncDoesNotOverwriteCopyIfAbsent(t *testing.T) {
	root := fixture(t)
	game := t.TempDir()
	out, _, _ := run(t, root, "--game", game)
	if !strings.Contains(out, "[sync-agents] hooks: .claude/settings.json を配りました") {
		t.Errorf("1 回目に配ったことを言っていない: %q", out)
	}
	write(t, game, ".claude/settings.json", "人が直した\n", 0o644)
	out, _, _ = run(t, root, "--game", game)
	if strings.Contains(out, "hooks:") {
		t.Errorf("2 回目に上書きしている: %q", out)
	}
	body, err := os.ReadFile(filepath.Join(game, ".claude", "settings.json"))
	if err != nil {
		t.Fatal(err)
	}
	if string(body) != "人が直した\n" {
		t.Errorf("既存を上書きした: %q", string(body))
	}
}

func TestSyncReportsRulesAndLints(t *testing.T) {
	root := fixture(t)
	game := t.TempDir()
	out, _, _ := run(t, root, "--game", game)
	if !strings.Contains(out, "[sync-agents] rules: a.md b.md\n") {
		t.Errorf("rules の一覧が名前順でない: %q", out)
	}
	if !strings.Contains(out, "[sync-agents] lint: bin/lint-fake.py\n") {
		t.Errorf("lint の一覧が違う: %q", out)
	}
}

func TestMissingGameDir(t *testing.T) {
	root := fixture(t)
	out, errOut, code := run(t, root, "--game", filepath.Join(t.TempDir(), "nope"))
	if code != 1 || out != "" {
		t.Fatalf("code=%d out=%q", code, out)
	}
	if !strings.HasPrefix(errOut, "error: ゲームのフォルダが見つかりません: ") {
		t.Errorf("断り方が違う: %q", errOut)
	}
}

func TestNoGameArg(t *testing.T) {
	root := fixture(t)
	_, errOut, code := run(t, root)
	if code != 1 {
		t.Fatalf("code=%d", code)
	}
	if errOut != "error: GAME を指定してください (make sync-agents GAME=/path/to/game)\n" {
		t.Errorf("断り方が違う: %q", errOut)
	}
}

func TestCheckManifestFindsMissingSrcAndDeadLink(t *testing.T) {
	root := fixture(t)
	write(t, root, "agents-pack/manifest.json",
		`{"copy":[{"src":"bin/nope.py","dst":"bin/nope.py"}],"copyIfAbsent":[],"copyDirs":[]}`, 0o644)
	out, errOut, code := run(t, root, "--check-manifest")
	if code != 1 || out != "" {
		t.Fatalf("code=%d out=%q", code, out)
	}
	want := "[sync-agents] NG: manifest の copy が指す bin/nope.py が engine に実在しません\n" +
		"[sync-agents] NG: docs/link.md が指す .claude/skills/nope/ は agents-pack/skills に実在しません\n"
	if errOut != want {
		t.Errorf("NG の出方が\n%q\n期待\n%q", errOut, want)
	}
}

func TestCheckManifestBrokenJSON(t *testing.T) {
	root := fixture(t)
	write(t, root, "agents-pack/manifest.json", `{"copy":[] "copyIfAbsent":[]}`, 0o644)
	_, errOut, code := run(t, root, "--check-manifest")
	if code != 1 {
		t.Fatalf("code=%d", code)
	}
	want := "[sync-agents] NG: agents-pack/manifest.json が読めません: " +
		"Expecting ',' delimiter: line 1 column 12 (char 11)\n"
	if errOut != want {
		t.Errorf("文面が\n%q\n期待\n%q", errOut, want)
	}
}

func TestCheckManifestKeyNotList(t *testing.T) {
	root := fixture(t)
	write(t, root, "agents-pack/manifest.json", `{"copy":{},"copyIfAbsent":[],"copyDirs":[]}`, 0o644)
	_, errOut, _ := run(t, root, "--check-manifest")
	if !strings.HasSuffix(errOut, "manifest に copy 配列がありません\n") {
		t.Errorf("文面が %q", errOut)
	}
}

func TestCheckManifestElementWithoutSrc(t *testing.T) {
	root := fixture(t)
	write(t, root, "agents-pack/manifest.json",
		`{"copy":[{"dst":"a"}],"copyIfAbsent":[],"copyDirs":[]}`, 0o644)
	_, errOut, _ := run(t, root, "--check-manifest")
	if !strings.HasSuffix(errOut, "copy の要素に src / dst がありません: {'dst': 'a'}\n") {
		t.Errorf("文面が %q", errOut)
	}
}

func TestCheckManifestMissingFileAborts(t *testing.T) {
	root := fixture(t)
	if err := os.Remove(filepath.Join(root, "agents-pack", "manifest.json")); err != nil {
		t.Fatal(err)
	}
	var out, errOut strings.Builder
	code, err := Run(&out, &errOut, root, []string{"--check-manifest"})
	if err != nil || code != 1 {
		t.Fatalf("code=%d err=%v", code, err)
	}
	if !strings.Contains(errOut.String(), "[Errno 2] No such file or directory: '") {
		t.Errorf("OSError の字面が違う: %q", errOut.String())
	}
}

func TestHelpGoesToStdout(t *testing.T) {
	root := fixture(t)
	out, errOut, code := run(t, root, "--help")
	if code != 0 || errOut != "" {
		t.Fatalf("code=%d err=%q", code, errOut)
	}
	if !strings.HasPrefix(out, "usage: sync-agents.py [-h]") || !strings.HasSuffix(out, "  --check-manifest\n") {
		t.Errorf("help が %q", out)
	}
}

func TestUnknownFlagGoesToStderr(t *testing.T) {
	root := fixture(t)
	out, errOut, code := run(t, root, "--bogus", "x")
	if code != 2 || out != "" {
		t.Fatalf("code=%d out=%q", code, out)
	}
	if !strings.HasSuffix(errOut, "sync-agents.py: error: unrecognized arguments: --bogus x\n") {
		t.Errorf("断り方が違う: %q", errOut)
	}
}

func TestFlagAbbreviation(t *testing.T) {
	root := fixture(t)
	shortOut, shortErr, shortCode := run(t, root, "--c")
	longOut, longErr, longCode := run(t, root, "--check-manifest")
	if shortOut != longOut || shortErr != longErr || shortCode != longCode {
		t.Errorf("--c が --check-manifest に解けていない: %q %q %d", shortOut, shortErr, shortCode)
	}
}

func TestFlagWithoutValue(t *testing.T) {
	root := fixture(t)
	_, errOut, code := run(t, root, "--game")
	if code != 2 {
		t.Fatalf("code=%d", code)
	}
	if !strings.HasSuffix(errOut, "sync-agents.py: error: argument --game: expected one argument\n") {
		t.Errorf("断り方が違う: %q", errOut)
	}
}

func TestTriggerSentence(t *testing.T) {
	r, err := LoadRules(repoRoot())
	if err != nil {
		t.Fatal(err)
	}
	for _, tc := range []struct{ in, want string }{
		{"能書き。〜のときに使う。補足。", "〜のときに使う。"},
		{"引き金の無い説明。おまけ。", "引き金の無い説明。"},
		{"", ""},
		{"。。。", "。。。"},
		{" 前後に空白 ", "前後に空白。"},
		{"使う ", "使う。"},
	} {
		if got := triggerSentence(r, tc.in); got != tc.want {
			t.Errorf("%q → %q (期待 %q)", tc.in, got, tc.want)
		}
	}
}

func TestSkillDescriptionMissingFile(t *testing.T) {
	desc, err := skillDescription(filepath.Join(t.TempDir(), "SKILL.md"))
	if err != nil || desc != "" {
		t.Errorf("desc=%q err=%v", desc, err)
	}
}

func TestPathHelpers(t *testing.T) {
	if got := pyName("bin/lint-view.py"); got != "lint-view.py" {
		t.Errorf("pyName が %s", got)
	}
	// WhyNot: filepath.Base と違って、末尾が / でも親の名前を返す。
	if got := pyName("bin/"); got != "bin" {
		t.Errorf("pyName が %s", got)
	}
	if got := pyName("/"); got != "" {
		t.Errorf("pyName が %q", got)
	}
	if got := pyParent("a/b/c"); got != "a/b" {
		t.Errorf("pyParent が %s", got)
	}
	if got := pyParent("a"); got != "." {
		t.Errorf("pyParent が %s", got)
	}
	if got := pyJoin("/root", "/abs"); got != "/abs" {
		t.Errorf("pyJoin が %s", got)
	}
	if got := pyJoin("/root", "a//b/"); got != "/root/a/b" {
		t.Errorf("pyJoin が %s", got)
	}
}

// WhyNot: 字面の比べ方にしないのは、パスの要素ごとに比べないと並びが変わるため。
func TestMdFilesSortedLikePython(t *testing.T) {
	root := t.TempDir()
	write(t, root, "a/b.md", "x", 0o644)
	write(t, root, "a-x/c.md", "x", 0o644)
	files, err := mdFilesSorted(root)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Join(files, ",") != "a/b.md,a-x/c.md" {
		t.Errorf("並びが %v", files)
	}
}

// copyDirs はミラー — 配り元に無い物は配り先から消える。
func TestCopyDirsRemovesFilesGoneFromSource(t *testing.T) {
	root := fixture(t)
	game := t.TempDir()
	run(t, root, "--game", game)
	write(t, game, ".claude/skills/zzz-stale/SKILL.md", "x\n", 0o644)
	write(t, game, ".claude/skills/alpha/stale-note.md", "x\n", 0o644)
	out, _, _ := run(t, root, "--game", game)

	for _, rel := range []string{".claude/skills/zzz-stale", ".claude/skills/alpha/stale-note.md"} {
		if _, err := os.Stat(filepath.Join(game, filepath.FromSlash(rel))); err == nil {
			t.Errorf("%s が消えていない", rel)
		}
	}
	if !strings.Contains(out, "[sync-agents] 消しました: .claude/skills/zzz-stale (配り元にありません)\n") {
		t.Errorf("消した物が報告に出ていない: %q", out)
	}
	if _, err := os.Stat(filepath.Join(game, ".claude", "skills", "alpha", "SKILL.md")); err != nil {
		t.Error("配り元にある物まで消してしまった")
	}
}

// ミラーにするのは copyDirs の配り先だけ。ゲームが自分で置いた物は消さない。
func TestPruneLeavesGameOwnedFiles(t *testing.T) {
	root := fixture(t)
	game := t.TempDir()
	write(t, game, "bin/my-tool.sh", "echo hi\n", 0o755)
	write(t, game, ".claude/settings.local.json", "{}\n", 0o644)
	run(t, root, "--game", game)
	run(t, root, "--game", game)
	for _, rel := range []string{"bin/my-tool.sh", ".claude/settings.local.json"} {
		if _, err := os.Stat(filepath.Join(game, filepath.FromSlash(rel))); err != nil {
			t.Errorf("人のファイル %s を消してしまった", rel)
		}
	}
}

// 配り元が空のときは何も消さない (engine 側の取り違えでゲームを空にしないため)。
func TestPruneSkippedWhenSourceEmpty(t *testing.T) {
	root := fixture(t)
	game := t.TempDir()
	run(t, root, "--game", game)
	src := filepath.Join(root, "agents-pack", "skills")
	if err := os.RemoveAll(src); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(src, 0o755); err != nil {
		t.Fatal(err)
	}
	run(t, root, "--game", game)
	if _, err := os.Stat(filepath.Join(game, ".claude", "skills", "alpha", "SKILL.md")); err != nil {
		t.Error("配り元が空なのに消してしまった")
	}
}

// symlink は辿らない (辿ると配り先の外の木を消しに行く)。
func TestPruneDoesNotFollowSymlinks(t *testing.T) {
	root := fixture(t)
	game := t.TempDir()
	outside := t.TempDir()
	write(t, outside, "keep.txt", "x\n", 0o644)
	run(t, root, "--game", game)
	link := filepath.Join(game, ".claude", "skills", "zzz-link")
	if err := os.Symlink(outside, link); err != nil {
		t.Skipf("symlink を作れない環境: %v", err)
	}
	run(t, root, "--game", game)
	if _, err := os.Lstat(link); err == nil {
		t.Error("配り元に無い symlink が残っている")
	}
	if _, err := os.Stat(filepath.Join(outside, "keep.txt")); err != nil {
		t.Error("symlink の先の木まで消してしまった")
	}
}
